# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vLeih7RQBiMh7ZsDBb5suvaDrJVnlnRq
"""

# Commented out IPython magic to ensure Python compatibility.
# This script was contributed by Lov

import numpy as np
import cv2 as cv
# %matplotlib inline
from matplotlib import pyplot as plt

def Night_time_img_enhancer_hard_coded(img_path) :
	import numpy as np
	import cv2 as cv
	# %matplotlib inline
	from matplotlib import pyplot as plt


	img = cv.imread(img_path,0)

	equ = cv.equalizeHist(img)
	res = np.hstack((img,equ))
	cv.imwrite('res.png',res)
	img1 = cv.imread('res.png',0)
	print(type(img1))
	# plt.imshow(img1)
	# plt.show()

	######

	# Commented out IPython magic to ensure Python compatibility.
	histr = cv.calcHist([img],[0],None,[256],[0,256]) 
	hist1 = cv.calcHist([img1],[0],None,[256],[0,256])


	#######

	# plt.plot(histr) 
	# plt.show() 
	# plt.plot(hist1) 
	# plt.show()

	#######

	clahe = cv.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
	cl1 = clahe.apply(img)

	cv.imwrite('clahe_2.jpg',cl1)
	img1= cv.imread('clahe_2.jpg',0)

	#######

	hist1 = cv.calcHist([img1],[0],None,[256],[0,256])  
	# plt.plot(hist1) 
	# plt.show()

	######

	import numpy as np
	import cv2 as cv
	# %matplotlib inline
	from matplotlib import pyplot as plt


	mg = cv.imread('2_1.jpg',0)

	equ = cv.equalizeHist(img)
	res = np.hstack((img,equ))
	cv.imwrite('res.png',res)
	img1 = cv.imread('res.png',0)
	print(type(img1))
	# plt.imshow(img1)
	# plt.show()


	histr = cv.calcHist([img],[0],None,[256],[0,256]) 
	hist1 = cv.calcHist([img1],[0],None,[256],[0,256])


	# plt.plot(histr) 
	# plt.show() 
	# plt.plot(hist1) 
	# plt.show()


	clahe = cv.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
	cl1 = clahe.apply(img)

	cv.imwrite('clahe_2.jpg',cl1)
	img1= cv.imread('clahe_2.jpg',0)


	hist1 = cv.calcHist([img1],[0],None,[256],[0,256])  
	# plt.plot(hist1) 
	# plt.show()

	#############

	comparison = cv.imread("res.png")

	try :
	  from google.colab.patches import cv2_imshow
	  cv2_imshow(comparison)
	except: 
	  cv.imshow(comparison)

img_path = ["1.png","2.png","3.png","4.png","5.png","6.png","7.png",]
Night_time_img_enhancer_hard_coded(img_path)